version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: trading-journal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: trading_journal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - trading-journal-network

  # Optional: Add pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trading-journal-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tradingjournal.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - trading-journal-network

volumes:
  postgres_data:

networks:
  trading-journal-network:
    driver: bridge
